-- 创建数据库
CREATE DATABASE IF NOT EXISTS ssm_crud DEFAULT CHARACTER SET='UTF8' ;

USE ssm_crud;

-- 创建用户表
CREATE TABLE IF NOT EXISTS user(
	id INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT "用户id",
	username VARCHAR(255) UNIQUE KEY NOT NULL COMMENT "用户名",
	password VARCHAR(255) NOT NULL COMMENT "密码",
	gender VARCHAR(1) NOT NULL COMMENT "性别",
	address VARCHAR(255) NOT NULL COMMENT "出生地/地址",
	birthday DATETIME NOT NULL COMMENT "出生日期",
	avatar VARCHAR(255) NOT NULL COMMENT "头像链接",
	hobbies VARCHAR(255) NOT NULL COMMENT "爱好,逗号分隔",
	reg_time DATETIME DEFAULT CURRENT_TIMESTAMP() COMMENT "创建时间"
)ENGINE=InnoDB CHARSET=UTF8;

-- 创建员工表
CREATE TABLE IF NOT EXISTS emp (
	emp_id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT "员工id",
	emp_name VARCHAR(255) NOT NULL COMMENT "员工姓名",
	emp_gender VARCHAR(1) NOT NULL COMMENT "员工性别",
	emp_email VARCHAR(255) COMMENT "员工邮箱",
	d_id INT(11) COMMENT "部门id"
)ENGINE=InnoDB CHARSET=UTF8;

-- 创建部门表
CREATE TABLE IF NOT EXISTS dept(
	dept_id INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT "部门id",
	dept_name VARCHAR(255) NOT NULL COMMENT "部门名称"
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

-- 创建日志表
CREATE TABLE IF NOT EXISTS log(
	id INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT "日志id",
	operator VARCHAR(255) NOT NULL COMMENT "操作者",
	type VARCHAR(255) NOT NULL COMMENT "操作类型",
	result VARCHAR(255) NOT NULL DEFAULT "成功" COMMENT "操作结果",
	opt_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT "操作时间"
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
