-- 创建数据库
CREATE DATABASE IF NOT EXISTS ssm_crud DEFAULT CHARACTER SET='UTF8' ;

USE ssm_crud;

-- 创建员工表
CREATE TABLE IF NOT EXISTS emp (
	emp_id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT "员工id",
	emp_name VARCHAR(255) NOT NULL COMMENT "员工姓名",
	emp_gender VARCHAR(1) NOT NULL COMMENT "员工性别",
	emp_email VARCHAR(255) COMMENT "员工邮箱",
	d_id INT(11) COMMENT "部门id"
)ENGINE=InnoDB CHARSET=UTF8;

-- 创建部门表
CREATE TABLE IF NOT EXISTS dept(
	dept_id INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT "部门id",
	dept_name VARCHAR(255) NOT NULL COMMENT "部门名称"
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
